# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('travelDateFrom', models.DateField()),
                ('travelDateTo', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='login.Login')),
            ],
        ),
        migrations.AddField(
            model_name='travel',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TripSelected', to='travelbuddy.Trip'),
        ),
        migrations.AddField(
            model_name='travel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonTraveling', to='login.Login'),
        ),
    ]
